"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 27;
let altura = 1.75;
const nacionalidade = 'Brasileira';
const colegas = ['Lucas', 'Fernanda', 'Marcio'];
const tecnologias = ['html', 'css', 'js'];
const notas = [7, 9, 5, 8];
const lista = ['ramon', true, 27];
let idadeDaAna = 25;
idadeDaAna = '25 anos';
let dadosDaApi;
dadosDaApi = 10;
dadosDaApi = 'string';
dadosDaApi = true;
dadosDaApi = [1, 2, 3];
